# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
 platform :ios, '11.1'

target 'DuitkuSDkIos_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'DuitkuSDkIos', :path => '../'
  
   # pod 'DuitkuSDkIos', '~> 0.0'
  #pod 'DuitkuSDkIos', '~> 0.2'


  # Pods for DuitkuSDkIos_Example

end
